### PR TITLE
Removed #cloud-boothook to execute UserData on instance start

### LINKED ISSUE #20: User Data not applied on first boot - instance unreachable via SSH and HTTP
When creating the environment with ./start.sh <ip-here> it runs as intended however the instance is later unreachable as the User-Data is not executed on the created instance. It required the instance to be rebooted, which then executed UserData as intended.

This was verified by removing `#cloud-boothook` from ec2.tf file, which will cause User data to execute on initial launch instead of every-other reboot.

### PR DESCRIPTION
**Pull request by LukaszMrozowski**
This fixes #20.

### CODE REVIEW

**Comment by LukaszMrozowski** [comment]
Please use - 6a84a3d or remove cloud-webhook in bash part of terraform.

**Comment by SpenGietz** [comment]
I apologize for the long delay here. I wanted the script to boot every time the instance was started up, but it definitely is more important for it to start the first time in this case. I'll merge this in, but I am definitely curious as to why this has stopped working, as it did for a long time previous.

**Comment by LukaszMrozowski** [comment]
No worries at all. I came across this problem as well and figured it out. Using Cloudinit was the right move to go to but as you said for some reason it stopped working. I realised that when launching UserData with a normal bash script works fine for the initial launch, but if you want UserData to execute every time afterwards you have to use cloud init. Below I includded snippets of what it would look like, hope its useful. 


Initial Launch UserData:
`    # https://www.base64decode.org/
    #!/bin/bash
    yum update -y
    yum install php -y
    yum install httpd -y
    mkdir -p /var/www/html
    cd /var/www/html
    rm -rf ./*
    printf "<?php\nif(isset(\$_POST['url'])) {\n  if(strcmp(\$_POST['password'], '12345') != 0) {\n    echo 'Wrong password. You just need to find it!';\n    die;\n  }\n  echo '<pre>';\n  echo(file_get_contents(\$_POST['url']));\n  echo '</pre>';\n  die;\n}\n?>\n<html><head><title>URL Fetcher</title></head><body><form method='POST'><label for='url'>Enter the password and a URL that you want to make a request to (ex: https://google.com/)</label><br /><input type='text' name='password' placeholder='Password' /><input type='text' name='url' placeholder='URL' /><br /><input type='submit' value='Retrieve Contents' /></form></body></html>" > index.php
    /usr/sbin/apachectl start`


Every launch after initial start up:
`# Create new UserData to send to instance, save this to a file
  # https://aws.amazon.com/premiumsupport/knowledge-center/execute-user-data-ec2/
  Content-Type: multipart/mixed; boundary="//"
  MIME-Version: 1.0

  --//
  Content-Type: text/cloud-config; charset="us-ascii"
  MIME-Version: 1.0
  Content-Transfer-Encoding: 7bit
  Content-Disposition: attachment; filename="cloud-config.txt"

  #cloud-config
  cloud_final_modules:
  - [scripts-user, always]

  --//
  Content-Type: text/x-shellscript; charset="us-ascii"
  MIME-Version: 1.0
  Content-Transfer-Encoding: 7bit
  Content-Disposition: attachment; filename="userdata.txt"

  #!/bin/bash
  rm -rf /var/lib/cloud/*
  yum update -y
  yum install php -y
  yum install httpd -y
  mkdir -p /var/www/html
  cd /var/www/html
  rm -rf ./*
  printf "<?php\nif(isset(\$_POST['url'])) {\n  if(strcmp(\$_POST['password'], '1234') != 0) {\n    echo 'Wrong password. You just need to find it!';\n    die;\n  }\n  echo '<pre>';\n  echo(file_get_contents(\$_POST['url']));\n  echo '</pre>';\n  die;\n}\n?>\n<html><head><title>URL Fetcher</title></head><body><form method='POST'><label for='url'>Enter the password and a URL that you want to make a request to (ex: https://google.com/)</label><br /><input type='text' name='password' placeholder='Password' /><input type='text' name='url' placeholder='URL' /><br /><input type='submit' value='Retrieve Contents' /></form></body></html>" > index.php
  /usr/sbin/apachectl start
  --//`


The MIME version of CloudInit is the only one I managed to get working, and it does execute on every reboot of the instance after intial provisioning.

**Comment by LukaszMrozowski** [comment]
Apologies for any rogue quotes. Was edited for my own use. Hope this helps.

**Pull request merged**
