### PR TITLE
resolves terraform version error

### PR DESCRIPTION
**Pull request by Kevin-byt**
#### Overview of Changes
- What was changed

#### Testing
Was this tested with different Terraform versions?

### CODE REVIEW

**Comment by Kevin-byt** [comment]
I constantly got the error "Terraform not found. Please install Terraform before using CloudGoat." when running the cloudgoat.py script but Terraform was already installed in my system. I realized that the error was on how the regex expression to derive the version was being handled, which I have edited

**Review by andrew-aiken — APPROVED** [review]
LGTM

Thanks for making the regex a little cleaner.

**Comment by Kevin-byt** [comment]
My pleasure. Thank you

**Review by TeneBrae93 — APPROVED** [review]

**Comment by TeneBrae93** [comment]
Thanks for this @Kevin-byt - And apologies for the delay. I'm spending today working through some Pull Requests. All of this looks good to me both in the code and testing. Thank you for your contribution!

**Pull request merged**
