### PR TITLE
CICD Scenario: Remove tf lock file and loosen dependencies

### LINKED ISSUE #128: Terraform Errors on creating CICD scenario.
Hi there,

I encountered a terraform error that I could not find a proper fix. 

I have done the following scenarios (not requiring extra resources) with no terraform issues except this CICD scenario:
- vulnerable_lambda
- iam_privesc_by_rollback
- cloud_breach_s3
- ec2_ssrf
- ecs_takeover
- rce_web_app
- ecs_efs_attack

cloudgoat_create_cicd_error

My terraform version is as follows:
```
╰─# terraform --version
Terraform v1.1.9
on linux_amd64
```

I was also not able to overcome the error with the suggested `terraform init -upgrade` in the CICD terraform folder as seen below.

cicd_terraform_init_upgrade

### PR DESCRIPTION
**Pull request by RyanJarv**
Resolves #128

This also resolves an issue where some commands might use the wrong profile. It seems in most cases this should fail, even if the incorrect profile is used, but I may need to look into this more.

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
@RyanJarv, change the => to >= , works well

But when i fixed one error now another error appears in CICD

can you check at your end to build from scratch ?

**Comment by RyanJarv** [comment]
@DhiyaneshGeek It may work for you now, however I didn't test the case where there is no default vpc/subnet so I'm not positive this will resolve the issue.. I'll have to double check that when I have some time if you continue to run into issues here.

**Comment by DhiyaneshGeek** [comment]
@RyanJarv while building it , i am facing this issue.

Are you able to successfully build the cicd vulnerable setup ?

image

**Comment by RyanJarv** [comment]
@DhiyaneshGeek just pushed a fix for this. Let me know if that resolves the issue.

**Comment by DhiyaneshGeek** [comment]
@RyanJarv Yeah it fixed the issue, let me complete the scenario and see if this works properly

**Review by DaveYesland — APPROVED** [review]

**Pull request merged**
