### PR TITLE
Update SQS Flag Shop Terraform

### PR DESCRIPTION
**Pull request by andrew-aiken**
#### Overview of Changes
- Remove unused data calls that were brought up [here](https://github.com/RhinoSecurityLabs/cloudgoat/pull/276#pullrequestreview-2410682441)
- Update all Terraform naming to be standardized
- Switch to a default tags block
- Update flag
- Move lambda and sql into source directory

#### Testing
Deployed with a newer version of Terraform (1.9.2)
Confirmed scenario plays out as intended

### CODE REVIEW

**Comment by andrew-aiken** [comment]
@TeneBrae93 @jdearmas Could you review the changes

**Comment by andrew-aiken** [comment]
@jdearmas Works as expected on my side (exporting the creds to env vars)

Based on the error it looks like you might now have copied the id/key/token correctly

**Review by jdearmas — APPROVED** [review]

**Comment by jdearmas** [comment]
@andrew-aiken,

Thank you very much for taking the time to contribute and help improve cloudgoat!

**Comment by jdearmas** [comment]
@andrew-aiken,

Thank you very much for taking the time to contribute and help improve cloudgoat!

**Pull request merged**
