### PR TITLE
Flagshop and rds snapshot add summary

### PR DESCRIPTION
**Pull request by West-wise**
#### Overview of Changes
- Added a summary of the two scenarios(sqs_flag_shop, rds_snapshot) to README.md

### CODE REVIEW

**Review by andrew-aiken — APPROVED** [review]
LGTM

**Review by andrew-aiken — CHANGES_REQUESTED** [review]
Could you move your entries so it follows easy/small -> hard/large

**Comment by West-wise** [comment]
> Could you move your entries so it follows easy/small -> hard/large

rearranged the order, is this correct?

**Comment by andrew-aiken** [comment]
> > Could you move your entries so it follows easy/small -> hard/large
> 
> rearranged the order, is this correct?

Yes looks good

**Review by jdearmas — APPROVED** [review]

**Pull request merged**
