### PR TITLE
docs: Add dollar sign to indicate that it is a shell script

### PR DESCRIPTION
**Pull request by Yaminyam**
#### Overview of Changes
For document unity, a dollar sign was added to indicate that it is a shell script.

### CODE REVIEW

**Comment by andrew-aiken** [comment]
Thanks for working on the document unity.
Personally I think that its better to not have the dollar sign in front of them since it causes issues when copy/pasting.

**Comment by Yaminyam** [comment]
@andrew-aiken  Your opinion makes a lot of sense too!
So, would it be better to unify it by removing existing dollar signs?

**Comment by andrew-aiken** [comment]
That would make sense (at least for code blocks)

@jdearmas whats your opinion on this?

**Comment by TeneBrae93** [comment]
Hey @Yaminyam -- sorry for the late response on this. I agree with @andrew-aiken. I think it's better to not have the dollar sign due to copy/pasting issues (I've ran into that myself on other projects). It would be good to remove the dollar sign for consistency.

**Pull request closed without merging**
